name: cumulocity-agent
version: 4.2.9
grade: stable
summary: Cumulocity Linux agent
description: Generic Linux agent for Cumulocity IoT integration.
base: core18

confinement: devmode

apps:
  cumulocity-agent:
    command: usr/bin/srwatchdogd $SNAP/usr/bin/cumulocity-agent 240
    plugs: [network]
    daemon: simple

parts:
  cumulocity:
    plugin: dump
    source: .
    organize:
      bin: usr/bin
      lua: usr/share/cumulocity-agent/lua
      srtemplate.txt: usr/share/cumulocity-agent/srtemplate.txt
      lib: usr/lib
      cumulocity-agent.conf: usr/share/cumulocity-agent/cumulocity-agent.conf
    stage-packages:
      - liblua5.3-0
      - libcurl4-gnutls-dev
