name: c8ydemo-agent
version: 1.0.1
confinement: devmode
summary: Cumulocity Linux agent
description: Generic Linux agent for Cumulocity IoT integration.

apps:
  c8ydemo-agent:
    command: usr/bin/srwatchdogd $SNAP/usr/bin/c8ydemo-agent 240
    plugs: [network]
    daemon: simple

parts:
  c8ydemo:
    plugin: copy
    files:
      bin: usr/bin
      lua: usr/share/c8ydemo/lua
      srtemplate.txt: usr/share/c8ydemo/srtemplate.txt
      c8ydemo.conf: usr/share/c8ydemo/c8ydemo.conf
  libsera:
    plugin: copy
    files:
      lib: usr/lib
