name: $AGENT-NAME
version: 1.0.1
confinement: devmode
summary: Cumulocity Linux agent
description: Generic Linux agent for Cumulocity IoT integration.

apps:
  c8ydemo-agent:
    command: usr/bin/srwatchdogd $SNAP/usr/bin/$AGENT_NAME 240
    plugs: [network]
    daemon: simple

parts:
  c8ydemo:
    plugin: copy
    files:
      bin: usr/bin
      lua: usr/share/$AGENT_NAME/lua
      srtemplate.txt: usr/share/$AGENT_NAME/srtemplate.txt
      c8ydemo.conf: usr/share/$AGENT_NAME/$AGENT_NAME.conf
  libsera:
    plugin: copy
    files:
      lib: usr/lib
